name       : youtube-viewer
version    : 3.10.7
release    : 38
source     :
    - https://github.com/trizen/youtube-viewer/archive/refs/tags/3.10.7.tar.gz : aa929b3157486587c70c6757d7995c8d6a0a89bc41a6c0fdb587aa3447c37c94
homepage   : https://github.com/trizen/youtube-viewer
license    : Artistic-2.0
component  : network.web
summary    : A lightweight application for searching and streaming videos from YouTube
description: |
    A lightweight application for searching and streaming videos from YouTube.
builddeps  :
    - perl-module-build
    - perl-test-pod
rundeps    :
    - libwww-perl
    - mpv
    - perl-file-sharedir
    - perl-gtk2
    - perl-gtk3
    - perl-json
    - perl-json-xs
    - perl-term-readline-gnu
    - perl-unicode-linebreak
    - yt-dlp
build      : |
    %perl_setup --gtk
install    : |
    %perl_install
    install -Dm00644 $workdir/share/gtk-youtube-viewer.desktop $installdir/usr/share/applications/gtk-youtube-viewer.desktop
    install -Dm00644 $workdir/share/icons/gtk-youtube-viewer.png $installdir/usr/share/pixmaps/gtk-youtube-viewer.png
check      : |
    $workdir/Build test
