name       : youtube-viewer
version    : 3.9.9
release    : 29
source     :
    - https://github.com/trizen/youtube-viewer/archive/refs/tags/3.9.9.tar.gz : 29a326b6496bc6e96840d3c854d79a3ffb9e6006a033f11478c1633c1ac48a8b
homepage   : https://github.com/trizen/youtube-viewer
license    : Artistic-2.0
component  : network.web
summary    : A lightweight application for searching and streaming videos from YouTube
description: |
    A lightweight application for searching and streaming videos from YouTube.
builddeps  :
    - perl-module-build
    - perl-test-pod
rundeps    :
    - libwww-perl
    - perl-file-sharedir
    - perl-gtk2
    - perl-gtk3
    - perl-json
    - perl-json-xs
    - perl-term-readline-gnu
    - perl-unicode-linebreak
    - yt-dlp
build      : |
    %perl_setup --gtk
install    : |
    %perl_install
    install -Dm00644 $workdir/share/gtk-youtube-viewer.desktop $installdir/usr/share/applications/gtk-youtube-viewer.desktop
    install -Dm00644 $workdir/share/icons/gtk-youtube-viewer.png $installdir/usr/share/pixmaps/gtk-youtube-viewer.png
check      : |
    $workdir/Build test
