name       : youtube-viewer
version    : 3.10.0
release    : 30
source     :
    - https://github.com/trizen/youtube-viewer/archive/refs/tags/3.10.0.tar.gz : 68a2bd03c1f9a01809505e9beef75b4f64119f3709b3fb9ae6343d8b50c0bc85
homepage   : https://github.com/trizen/youtube-viewer
license    : Artistic-2.0
component  : network.web
summary    : A lightweight application for searching and streaming videos from YouTube
description: |
    A lightweight application for searching and streaming videos from YouTube.
builddeps  :
    - perl-module-build
    - perl-test-pod
rundeps    :
    - libwww-perl
    - perl-file-sharedir
    - perl-gtk2
    - perl-gtk3
    - perl-json
    - perl-json-xs
    - perl-term-readline-gnu
    - perl-unicode-linebreak
    - yt-dlp
build      : |
    %perl_setup --gtk
install    : |
    %perl_install
    install -Dm00644 $workdir/share/gtk-youtube-viewer.desktop $installdir/usr/share/applications/gtk-youtube-viewer.desktop
    install -Dm00644 $workdir/share/icons/gtk-youtube-viewer.png $installdir/usr/share/pixmaps/gtk-youtube-viewer.png
check      : |
    $workdir/Build test
